Update Gitpod ports
ddev/ddev-gitpod-launcher pull request #42
Opened 2024-06-24 08:44 UTC by tyler36

## The Issue
I was debugging Mailpit issues in Gitpod when I noticed many of the ports are outdated.

## How This PR Solves The Issue
This PR 

- updates the ports to match those from
https://github.com/ddev/ddev/blob/master/.gitpod.yml
- adds postgres port

This PR does NOT update the Mailpit port. See #40

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2024-06-24 23:56 UTC, tyler36 commented
OK. Not sure what changes you would like here though.

2024-06-24 23:59 UTC, rfay commented
There is no way to change it here, as it needs to be changed in DDEV. 

But I'm not sure why it needs to be changed. Is it `ddev mailpit` that needs to be changed? What is the goal?

2024-06-25 00:23 UTC, tyler36 commented
Consistency, mostly. 

EG. Xdebug port:

- FIle lists `9000` as xdebug port, but xdebug is on `9003`. So this is confusing.
- If it doesn't matter (ie, we don't use it), lets delete the entry so there's less maintainance.

2024-06-25 01:42 UTC, rfay commented
Xdebug has been on 9003 for several years, since before gitpod support. I'm wondering how it got that?

If you can live with mailpit listening on 8027, it's OK there. People shouldn't have to know where these ports are.

2024-06-25 01:46 UTC, rfay commented
Sorry, I got confused between your two PRs

2024-07-22 00:51 UTC, tyler36 commented
So where are we with this?

2024-07-22 10:36 UTC, stasadev commented
I think it's good.

Can you also add more ports from the official add-ons?:

- https://github.com/ddev/ddev-adminer
- https://github.com/ddev/ddev-xhgui

2024-07-23 03:31 UTC, tyler36 commented
Added ports but have not tested.

2024-07-23 09:22 UTC, stasadev requested changes
Thanks, I see you added HTTPS ports, but we also need HTTP, right?
For `docker-compose.*_norouter.yaml` that uses HTTP.

2024-07-23 09:22 UTC, stasadev commented on .gitpod.yml
> +  - port: 8142
```suggestion
  # xhgui http port
  - port: 8143
    onOpen: ignore
  # xhgui https port
  - port: 8142
```

2024-07-23 09:22 UTC, stasadev commented on .gitpod.yml
> +  - port: 9101
```suggestion
  # Adminer http port
  - port: 9100
    onOpen: ignore
  # Adminer https port
  - port: 9101
```

2024-07-24 00:06 UTC, tyler36 commented
@stasadev Oops. Forgot the HTTP ports. Good catch!

2024-07-24 17:38 UTC, stasadev approved these changes
Looks good to me.

2024-08-02 03:06 UTC, merged